name: Hugo

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and update Hugo themes
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.81.0"
          extended: true

      - name: Build Hugo
        run: hugo --minify

      - name: List files in build directory
        run: ls -lavh ./public

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.PH1SHER_CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.PH1SHER_CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'index-page'
          directory: 'public'
